/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * com.gdgguadalajara.pos API
 * OpenAPI spec version: 1.0.0-SNAPSHOT
 */
import type { Uuid } from './uuid';
import type { AccountStatus } from './accountStatus';
import type { AccountRole } from './accountRole';
import type { User } from './user';
import type { LocalDateTime } from './localDateTime';

export interface Account {
  id?: Uuid;
  username?: string;
  status?: AccountStatus;
  role?: AccountRole;
  user?: User;
  createdAt?: LocalDateTime;
  updatedAt?: LocalDateTime;
}
