/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * com.gdgguadalajara.pos API
 * OpenAPI spec version: 1.0.0-SNAPSHOT
 */

export type AccountRole = typeof AccountRole[keyof typeof AccountRole];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const AccountRole = {
  ADMIN: 'ADMIN',
  WAITER: 'WAITER',
  CASHIER: 'CASHIER',
} as const;
