/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * com.gdgguadalajara.pos API
 * OpenAPI spec version: 1.0.0-SNAPSHOT
 */
import type { User } from './user';

export interface AuthenticateResponse {
  token?: string;
  user?: User;
}
