/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * com.gdgguadalajara.pos API
 * OpenAPI spec version: 1.0.0-SNAPSHOT
 */
import type { Uuid } from './uuid';
import type { LocalDate } from './localDate';
import type { LocalTime } from './localTime';
import type { DayOfWeek } from './dayOfWeek';
import type { LocalDateTime } from './localDateTime';

export interface Category {
  id?: Uuid;
  name?: string;
  description?: string;
  isEnabled?: boolean;
  availableFrom?: LocalDate;
  availableUntil?: LocalDate;
  availableFromTime?: LocalTime;
  availableUntilTime?: LocalTime;
  availableDays?: DayOfWeek[];
  createdAt?: LocalDateTime;
  updatedAt?: LocalDateTime;
}
