/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * pos API
 * OpenAPI spec version: 1.0.0-SNAPSHOT
 */
import type { AccountRole } from './accountRole';

export interface CreateAccountRequest {
  username?: string;
  name?: string;
  email?: string;
  password?: string;
  isActive?: boolean;
  role?: AccountRole;
}
