/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * com.gdgguadalajara.pos API
 * OpenAPI spec version: 1.0.0-SNAPSHOT
 */
import type { AccountRole } from './accountRole';

export interface CreateInvitationRequest {
  /** @pattern ^\p{L}+(?: \p{L}+)*$ */
  name: string;
  /** @pattern \S */
  email: string;
  role: AccountRole;
}
