/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * com.gdgguadalajara.pos API
 * OpenAPI spec version: 1.0.0-SNAPSHOT
 */
import type { Uuid } from './uuid';
import type { RestaurantTable } from './restaurantTable';

export interface Floor {
  id?: Uuid;
  name?: string;
  levelOrder?: number;
  gridWidth?: number;
  gridHeight?: number;
  tables?: RestaurantTable[];
}
