/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * com.gdgguadalajara.pos API
 * OpenAPI spec version: 1.0.0-SNAPSHOT
 */
import type { Uuid } from './uuid';
import type { User } from './user';
import type { LocalDateTime } from './localDateTime';

export interface Invitation {
  id?: Uuid;
  token?: string;
  user?: User;
  expiresAt?: LocalDateTime;
  usedAt?: LocalDateTime;
  createdAt?: LocalDateTime;
  valid?: boolean;
}
