/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * com.gdgguadalajara.pos API
 * OpenAPI spec version: 1.0.0-SNAPSHOT
 */

export interface PaginationMeta {
  totalRecords?: number;
  currentPage?: number;
  totalPages?: number;
  nextPage?: number;
  prevPage?: number;
}
