/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * com.gdgguadalajara.pos API
 * OpenAPI spec version: 1.0.0-SNAPSHOT
 */
import type { Product } from './product';
import type { PaginationMeta } from './paginationMeta';

export interface PaginatedResponseProduct {
  data?: Product[];
  meta?: PaginationMeta;
}
