/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * com.gdgguadalajara.pos API
 * OpenAPI spec version: 1.0.0-SNAPSHOT
 */
import type { Uuid } from './uuid';
import type { RestaurantTableStatus } from './restaurantTableStatus';
import type { Floor } from './floor';

export interface RestaurantTable {
  id?: Uuid;
  name?: string;
  posX?: number;
  posY?: number;
  width?: number;
  height?: number;
  status?: RestaurantTableStatus;
  floor?: Floor;
}
