/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * com.gdgguadalajara.pos API
 * OpenAPI spec version: 1.0.0-SNAPSHOT
 */

export type RestaurantTableStatus = typeof RestaurantTableStatus[keyof typeof RestaurantTableStatus];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const RestaurantTableStatus = {
  AVAILABLE: 'AVAILABLE',
  OCCUPIED: 'OCCUPIED',
  RESERVED: 'RESERVED',
  CLEANING: 'CLEANING',
  NOT_AVAILABLE: 'NOT_AVAILABLE',
} as const;
