/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * com.gdgguadalajara.pos API
 * OpenAPI spec version: 1.0.0-SNAPSHOT
 */
import type { Uuid } from './uuid';
import type { User } from './user';
import type { RestaurantTable } from './restaurantTable';
import type { TicketStatus } from './ticketStatus';
import type { TicketItem } from './ticketItem';
import type { LocalDateTime } from './localDateTime';

export interface Ticket {
  id?: Uuid;
  owner?: User;
  table?: RestaurantTable;
  dinerCount?: number;
  totalAmount?: number;
  status?: TicketStatus;
  items?: TicketItem[];
  createdAt?: LocalDateTime;
  updatedAt?: LocalDateTime;
  closedAt?: LocalDateTime;
}
