/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * com.gdgguadalajara.pos API
 * OpenAPI spec version: 1.0.0-SNAPSHOT
 */
import type { Uuid } from './uuid';
import type { Ticket } from './ticket';
import type { User } from './user';
import type { TicketItemStatus } from './ticketItemStatus';
import type { TicketItemProductSnapshot } from './ticketItemProductSnapshot';
import type { LocalDateTime } from './localDateTime';

export interface TicketItem {
  id?: Uuid;
  ticket?: Ticket;
  author?: User;
  originalProductId?: Uuid;
  productName?: string;
  unitPrice?: number;
  status?: TicketItemStatus;
  productSnapshot?: TicketItemProductSnapshot;
  createdAt?: LocalDateTime;
  updatedAt?: LocalDateTime;
}
