/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * com.gdgguadalajara.pos API
 * OpenAPI spec version: 1.0.0-SNAPSHOT
 */
import type { Uuid } from './uuid';
import type { Account } from './account';
import type { LocalDateTime } from './localDateTime';

export interface User {
  id?: Uuid;
  name?: string;
  email?: string;
  account?: Account;
  createdAt?: LocalDateTime;
  updatedAt?: LocalDateTime;
}
