/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * com.gdgguadalajara.pos API
 * OpenAPI spec version: 1.0.0-SNAPSHOT
 */
import type {
  Category,
  Product,
  Uuid
} from '../../models';

import { customFetch } from '.././CustomFetch';

/**
 * @summary Read Product Categories
 */
export type getApiProductsProductIdCategoriesResponse200 = {
  data: Category[]
  status: 200
}

export type getApiProductsProductIdCategoriesResponse401 = {
  data: void
  status: 401
}

export type getApiProductsProductIdCategoriesResponse403 = {
  data: void
  status: 403
}
    
export type getApiProductsProductIdCategoriesResponseSuccess = (getApiProductsProductIdCategoriesResponse200) & {
  headers: Headers;
};
export type getApiProductsProductIdCategoriesResponseError = (getApiProductsProductIdCategoriesResponse401 | getApiProductsProductIdCategoriesResponse403) & {
  headers: Headers;
};

export type getApiProductsProductIdCategoriesResponse = (getApiProductsProductIdCategoriesResponseSuccess | getApiProductsProductIdCategoriesResponseError)

export const getGetApiProductsProductIdCategoriesUrl = (productId: Uuid,) => {


  

  return `/api/products/${productId}/categories`
}

export const getApiProductsProductIdCategories = async (productId: Uuid, options?: RequestInit): Promise<getApiProductsProductIdCategoriesResponse> => {
  
  return customFetch<getApiProductsProductIdCategoriesResponse>(getGetApiProductsProductIdCategoriesUrl(productId),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}


/**
 * @summary Remove
 */
export type deleteApiProductsProductIdCategoriesCategoryIdResponse204 = {
  data: void
  status: 204
}

export type deleteApiProductsProductIdCategoriesCategoryIdResponse401 = {
  data: void
  status: 401
}

export type deleteApiProductsProductIdCategoriesCategoryIdResponse403 = {
  data: void
  status: 403
}
    
export type deleteApiProductsProductIdCategoriesCategoryIdResponseSuccess = (deleteApiProductsProductIdCategoriesCategoryIdResponse204) & {
  headers: Headers;
};
export type deleteApiProductsProductIdCategoriesCategoryIdResponseError = (deleteApiProductsProductIdCategoriesCategoryIdResponse401 | deleteApiProductsProductIdCategoriesCategoryIdResponse403) & {
  headers: Headers;
};

export type deleteApiProductsProductIdCategoriesCategoryIdResponse = (deleteApiProductsProductIdCategoriesCategoryIdResponseSuccess | deleteApiProductsProductIdCategoriesCategoryIdResponseError)

export const getDeleteApiProductsProductIdCategoriesCategoryIdUrl = (productId: Uuid,
    categoryId: Uuid,) => {


  

  return `/api/products/${productId}/categories/${categoryId}`
}

export const deleteApiProductsProductIdCategoriesCategoryId = async (productId: Uuid,
    categoryId: Uuid, options?: RequestInit): Promise<deleteApiProductsProductIdCategoriesCategoryIdResponse> => {
  
  return customFetch<deleteApiProductsProductIdCategoriesCategoryIdResponse>(getDeleteApiProductsProductIdCategoriesCategoryIdUrl(productId,categoryId),
  {      
    ...options,
    method: 'DELETE'
    
    
  }
);}


/**
 * @summary Create
 */
export type postApiProductsProductIdCategoriesCategoryIdResponse200 = {
  data: Product
  status: 200
}

export type postApiProductsProductIdCategoriesCategoryIdResponse401 = {
  data: void
  status: 401
}

export type postApiProductsProductIdCategoriesCategoryIdResponse403 = {
  data: void
  status: 403
}
    
export type postApiProductsProductIdCategoriesCategoryIdResponseSuccess = (postApiProductsProductIdCategoriesCategoryIdResponse200) & {
  headers: Headers;
};
export type postApiProductsProductIdCategoriesCategoryIdResponseError = (postApiProductsProductIdCategoriesCategoryIdResponse401 | postApiProductsProductIdCategoriesCategoryIdResponse403) & {
  headers: Headers;
};

export type postApiProductsProductIdCategoriesCategoryIdResponse = (postApiProductsProductIdCategoriesCategoryIdResponseSuccess | postApiProductsProductIdCategoriesCategoryIdResponseError)

export const getPostApiProductsProductIdCategoriesCategoryIdUrl = (productId: Uuid,
    categoryId: Uuid,) => {


  

  return `/api/products/${productId}/categories/${categoryId}`
}

export const postApiProductsProductIdCategoriesCategoryId = async (productId: Uuid,
    categoryId: Uuid, options?: RequestInit): Promise<postApiProductsProductIdCategoriesCategoryIdResponse> => {
  
  return customFetch<postApiProductsProductIdCategoriesCategoryIdResponse>(getPostApiProductsProductIdCategoriesCategoryIdUrl(productId,categoryId),
  {      
    ...options,
    method: 'POST'
    
    
  }
);}


