/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * com.gdgguadalajara.pos API
 * OpenAPI spec version: 1.0.0-SNAPSHOT
 */
import type {
  CreateProductRequest,
  GetApiProductsParams,
  PaginatedResponseProduct,
  Product,
  UpdateProductRequest,
  Uuid
} from '../../models';

import { customFetch } from '.././CustomFetch';

/**
 * @summary Read
 */
export type getApiProductsResponse200 = {
  data: PaginatedResponseProduct
  status: 200
}

export type getApiProductsResponse401 = {
  data: void
  status: 401
}

export type getApiProductsResponse403 = {
  data: void
  status: 403
}
    
export type getApiProductsResponseSuccess = (getApiProductsResponse200) & {
  headers: Headers;
};
export type getApiProductsResponseError = (getApiProductsResponse401 | getApiProductsResponse403) & {
  headers: Headers;
};

export type getApiProductsResponse = (getApiProductsResponseSuccess | getApiProductsResponseError)

export const getGetApiProductsUrl = (params?: GetApiProductsParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/api/products?${stringifiedParams}` : `/api/products`
}

export const getApiProducts = async (params?: GetApiProductsParams, options?: RequestInit): Promise<getApiProductsResponse> => {
  
  return customFetch<getApiProductsResponse>(getGetApiProductsUrl(params),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}


/**
 * @summary Create
 */
export type postApiProductsResponse200 = {
  data: Product
  status: 200
}

export type postApiProductsResponse400 = {
  data: void
  status: 400
}

export type postApiProductsResponse401 = {
  data: void
  status: 401
}

export type postApiProductsResponse403 = {
  data: void
  status: 403
}
    
export type postApiProductsResponseSuccess = (postApiProductsResponse200) & {
  headers: Headers;
};
export type postApiProductsResponseError = (postApiProductsResponse400 | postApiProductsResponse401 | postApiProductsResponse403) & {
  headers: Headers;
};

export type postApiProductsResponse = (postApiProductsResponseSuccess | postApiProductsResponseError)

export const getPostApiProductsUrl = () => {


  

  return `/api/products`
}

export const postApiProducts = async (createProductRequest: CreateProductRequest, options?: RequestInit): Promise<postApiProductsResponse> => {
  
  return customFetch<postApiProductsResponse>(getPostApiProductsUrl(),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      createProductRequest,)
  }
);}


/**
 * @summary Update
 */
export type putApiProductsUuidResponse200 = {
  data: Product
  status: 200
}

export type putApiProductsUuidResponse400 = {
  data: void
  status: 400
}

export type putApiProductsUuidResponse401 = {
  data: void
  status: 401
}

export type putApiProductsUuidResponse403 = {
  data: void
  status: 403
}
    
export type putApiProductsUuidResponseSuccess = (putApiProductsUuidResponse200) & {
  headers: Headers;
};
export type putApiProductsUuidResponseError = (putApiProductsUuidResponse400 | putApiProductsUuidResponse401 | putApiProductsUuidResponse403) & {
  headers: Headers;
};

export type putApiProductsUuidResponse = (putApiProductsUuidResponseSuccess | putApiProductsUuidResponseError)

export const getPutApiProductsUuidUrl = (uuid: Uuid,) => {


  

  return `/api/products/${uuid}`
}

export const putApiProductsUuid = async (uuid: Uuid,
    updateProductRequest: UpdateProductRequest, options?: RequestInit): Promise<putApiProductsUuidResponse> => {
  
  return customFetch<putApiProductsUuidResponse>(getPutApiProductsUuidUrl(uuid),
  {      
    ...options,
    method: 'PUT',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      updateProductRequest,)
  }
);}


/**
 * @summary Read By Id
 */
export type getApiProductsUuidResponse200 = {
  data: Product
  status: 200
}

export type getApiProductsUuidResponse401 = {
  data: void
  status: 401
}

export type getApiProductsUuidResponse403 = {
  data: void
  status: 403
}
    
export type getApiProductsUuidResponseSuccess = (getApiProductsUuidResponse200) & {
  headers: Headers;
};
export type getApiProductsUuidResponseError = (getApiProductsUuidResponse401 | getApiProductsUuidResponse403) & {
  headers: Headers;
};

export type getApiProductsUuidResponse = (getApiProductsUuidResponseSuccess | getApiProductsUuidResponseError)

export const getGetApiProductsUuidUrl = (uuid: Uuid,) => {


  

  return `/api/products/${uuid}`
}

export const getApiProductsUuid = async (uuid: Uuid, options?: RequestInit): Promise<getApiProductsUuidResponse> => {
  
  return customFetch<getApiProductsUuidResponse>(getGetApiProductsUuidUrl(uuid),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}


/**
 * @summary Delete
 */
export type deleteApiProductsUuidResponse204 = {
  data: void
  status: 204
}

export type deleteApiProductsUuidResponse401 = {
  data: void
  status: 401
}

export type deleteApiProductsUuidResponse403 = {
  data: void
  status: 403
}
    
export type deleteApiProductsUuidResponseSuccess = (deleteApiProductsUuidResponse204) & {
  headers: Headers;
};
export type deleteApiProductsUuidResponseError = (deleteApiProductsUuidResponse401 | deleteApiProductsUuidResponse403) & {
  headers: Headers;
};

export type deleteApiProductsUuidResponse = (deleteApiProductsUuidResponseSuccess | deleteApiProductsUuidResponseError)

export const getDeleteApiProductsUuidUrl = (uuid: Uuid,) => {


  

  return `/api/products/${uuid}`
}

export const deleteApiProductsUuid = async (uuid: Uuid, options?: RequestInit): Promise<deleteApiProductsUuidResponse> => {
  
  return customFetch<deleteApiProductsUuidResponse>(getDeleteApiProductsUuidUrl(uuid),
  {      
    ...options,
    method: 'DELETE'
    
    
  }
);}


