/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * com.gdgguadalajara.pos API
 * OpenAPI spec version: 1.0.0-SNAPSHOT
 */
import type {
  Ticket,
  Uuid
} from '../../models';

import { customFetch } from '.././CustomFetch';

/**
 * @summary Create
 */
export type postApiTicketsResponse200 = {
  data: Ticket
  status: 200
}

export type postApiTicketsResponse401 = {
  data: void
  status: 401
}

export type postApiTicketsResponse403 = {
  data: void
  status: 403
}
    
export type postApiTicketsResponseSuccess = (postApiTicketsResponse200) & {
  headers: Headers;
};
export type postApiTicketsResponseError = (postApiTicketsResponse401 | postApiTicketsResponse403) & {
  headers: Headers;
};

export type postApiTicketsResponse = (postApiTicketsResponseSuccess | postApiTicketsResponseError)

export const getPostApiTicketsUrl = () => {


  

  return `/api/tickets`
}

export const postApiTickets = async ( options?: RequestInit): Promise<postApiTicketsResponse> => {
  
  return customFetch<postApiTicketsResponse>(getPostApiTicketsUrl(),
  {      
    ...options,
    method: 'POST'
    
    
  }
);}


/**
 * @summary Read By Id
 */
export type getApiTicketsIdResponse200 = {
  data: Ticket
  status: 200
}

export type getApiTicketsIdResponse401 = {
  data: void
  status: 401
}

export type getApiTicketsIdResponse403 = {
  data: void
  status: 403
}
    
export type getApiTicketsIdResponseSuccess = (getApiTicketsIdResponse200) & {
  headers: Headers;
};
export type getApiTicketsIdResponseError = (getApiTicketsIdResponse401 | getApiTicketsIdResponse403) & {
  headers: Headers;
};

export type getApiTicketsIdResponse = (getApiTicketsIdResponseSuccess | getApiTicketsIdResponseError)

export const getGetApiTicketsIdUrl = (id: Uuid,) => {


  

  return `/api/tickets/${id}`
}

export const getApiTicketsId = async (id: Uuid, options?: RequestInit): Promise<getApiTicketsIdResponse> => {
  
  return customFetch<getApiTicketsIdResponse>(getGetApiTicketsIdUrl(id),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}


