/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * com.gdgguadalajara.pos API
 * OpenAPI spec version: 1.0.0-SNAPSHOT
 */
import type {
  Category,
  Product,
  Uuid
} from '../../models';

import { customFetch } from '.././CustomFetch';

/**
 * @summary Get Category Products
 */
export type getApiCategoriesCategoryIdProductsResponse200 = {
  data: Product[]
  status: 200
}

export type getApiCategoriesCategoryIdProductsResponse401 = {
  data: void
  status: 401
}

export type getApiCategoriesCategoryIdProductsResponse403 = {
  data: void
  status: 403
}
    
export type getApiCategoriesCategoryIdProductsResponseSuccess = (getApiCategoriesCategoryIdProductsResponse200) & {
  headers: Headers;
};
export type getApiCategoriesCategoryIdProductsResponseError = (getApiCategoriesCategoryIdProductsResponse401 | getApiCategoriesCategoryIdProductsResponse403) & {
  headers: Headers;
};

export type getApiCategoriesCategoryIdProductsResponse = (getApiCategoriesCategoryIdProductsResponseSuccess | getApiCategoriesCategoryIdProductsResponseError)

export const getGetApiCategoriesCategoryIdProductsUrl = (categoryId: Uuid,) => {


  

  return `/api/categories/${categoryId}/products`
}

export const getApiCategoriesCategoryIdProducts = async (categoryId: Uuid, options?: RequestInit): Promise<getApiCategoriesCategoryIdProductsResponse> => {
  
  return customFetch<getApiCategoriesCategoryIdProductsResponse>(getGetApiCategoriesCategoryIdProductsUrl(categoryId),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}


/**
 * @summary Delete
 */
export type deleteApiCategoriesCategoryIdProductsProductIdResponse204 = {
  data: void
  status: 204
}

export type deleteApiCategoriesCategoryIdProductsProductIdResponse401 = {
  data: void
  status: 401
}

export type deleteApiCategoriesCategoryIdProductsProductIdResponse403 = {
  data: void
  status: 403
}
    
export type deleteApiCategoriesCategoryIdProductsProductIdResponseSuccess = (deleteApiCategoriesCategoryIdProductsProductIdResponse204) & {
  headers: Headers;
};
export type deleteApiCategoriesCategoryIdProductsProductIdResponseError = (deleteApiCategoriesCategoryIdProductsProductIdResponse401 | deleteApiCategoriesCategoryIdProductsProductIdResponse403) & {
  headers: Headers;
};

export type deleteApiCategoriesCategoryIdProductsProductIdResponse = (deleteApiCategoriesCategoryIdProductsProductIdResponseSuccess | deleteApiCategoriesCategoryIdProductsProductIdResponseError)

export const getDeleteApiCategoriesCategoryIdProductsProductIdUrl = (categoryId: Uuid,
    productId: Uuid,) => {


  

  return `/api/categories/${categoryId}/products/${productId}`
}

export const deleteApiCategoriesCategoryIdProductsProductId = async (categoryId: Uuid,
    productId: Uuid, options?: RequestInit): Promise<deleteApiCategoriesCategoryIdProductsProductIdResponse> => {
  
  return customFetch<deleteApiCategoriesCategoryIdProductsProductIdResponse>(getDeleteApiCategoriesCategoryIdProductsProductIdUrl(categoryId,productId),
  {      
    ...options,
    method: 'DELETE'
    
    
  }
);}


/**
 * @summary Create
 */
export type postApiCategoriesCategoryIdProductsProductIdResponse200 = {
  data: Category
  status: 200
}

export type postApiCategoriesCategoryIdProductsProductIdResponse401 = {
  data: void
  status: 401
}

export type postApiCategoriesCategoryIdProductsProductIdResponse403 = {
  data: void
  status: 403
}
    
export type postApiCategoriesCategoryIdProductsProductIdResponseSuccess = (postApiCategoriesCategoryIdProductsProductIdResponse200) & {
  headers: Headers;
};
export type postApiCategoriesCategoryIdProductsProductIdResponseError = (postApiCategoriesCategoryIdProductsProductIdResponse401 | postApiCategoriesCategoryIdProductsProductIdResponse403) & {
  headers: Headers;
};

export type postApiCategoriesCategoryIdProductsProductIdResponse = (postApiCategoriesCategoryIdProductsProductIdResponseSuccess | postApiCategoriesCategoryIdProductsProductIdResponseError)

export const getPostApiCategoriesCategoryIdProductsProductIdUrl = (categoryId: Uuid,
    productId: Uuid,) => {


  

  return `/api/categories/${categoryId}/products/${productId}`
}

export const postApiCategoriesCategoryIdProductsProductId = async (categoryId: Uuid,
    productId: Uuid, options?: RequestInit): Promise<postApiCategoriesCategoryIdProductsProductIdResponse> => {
  
  return customFetch<postApiCategoriesCategoryIdProductsProductIdResponse>(getPostApiCategoriesCategoryIdProductsProductIdUrl(categoryId,productId),
  {      
    ...options,
    method: 'POST'
    
    
  }
);}


