CREATE TABLE PUBLIC.CATEGORY (
	AVAILABLEFROM DATE NOT NULL,
	AVAILABLEFROMTIME TIME NOT NULL,
	AVAILABLEUNTIL DATE NOT NULL,
	AVAILABLEUNTILTIME TIME NOT NULL,
	ISENABLED BOOLEAN NOT NULL,
	CREATEDAT TIMESTAMP NOT NULL,
	UPDATEDAT TIMESTAMP,
	ID UUID NOT NULL,
	DESCRIPTION CHARACTER VARYING(255) NOT NULL,
	NAME CHARACTER VARYING(255) NOT NULL,
	CONSTRAINT CONSTRAINT_3 PRIMARY KEY (ID)
);

CREATE TABLE PUBLIC.FLOOR (
	GRIDHEIGHT INTEGER NOT NULL,
	GRIDWIDTH INTEGER NOT NULL,
	LEVELORDER INTEGER NOT NULL,
	CREATEDAT TIMESTAMP NOT NULL,
	UPDATEDAT TIMESTAMP,
	ID UUID NOT NULL,
	NAME CHARACTER VARYING(255) NOT NULL,
	CONSTRAINT CONSTRAINT_3F PRIMARY KEY (ID)
);

CREATE TABLE PUBLIC.PRODUCT (
	AVAILABLEFROM DATE NOT NULL,
	AVAILABLEFROMTIME TIME NOT NULL,
	AVAILABLEUNTIL DATE NOT NULL,
	AVAILABLEUNTILTIME TIME NOT NULL,
	ISENABLED BOOLEAN NOT NULL,
	PRICE NUMERIC(38,2) NOT NULL,
	CREATEDAT TIMESTAMP NOT NULL,
	UPDATEDAT TIMESTAMP,
	ID UUID NOT NULL,
	DESCRIPTION CHARACTER VARYING(255) NOT NULL,
	NAME CHARACTER VARYING(255) NOT NULL,
	CONSTRAINT CONSTRAINT_1 PRIMARY KEY (ID)
);

CREATE TABLE PUBLIC.USER_POS (
	CREATEDAT TIMESTAMP NOT NULL,
	UPDATEDAT TIMESTAMP,
	ID UUID NOT NULL,
	EMAIL CHARACTER VARYING(255) NOT NULL,
	NAME CHARACTER VARYING(255) NOT NULL,
	CONSTRAINT CONSTRAINT_1E UNIQUE (EMAIL),
	CONSTRAINT CONSTRAINT_1ED PRIMARY KEY (ID)
);

CREATE TABLE PUBLIC.ACCOUNT (
	CREATEDAT TIMESTAMP NOT NULL,
	UPDATEDAT TIMESTAMP,
	ID UUID NOT NULL,
	USER_ID UUID,
	PASSWORD CHARACTER VARYING(255),
	USERNAME CHARACTER VARYING(255) NOT NULL,
	"ROLE" ENUM('ADMIN', 'CASHIER', 'WAITER') NOT NULL,
	STATUS ENUM('ACTIVE', 'DISABLED', 'LOCKED', 'PENDING_SETUP') NOT NULL,
	CONSTRAINT CONSTRAINT_E UNIQUE (USER_ID),
	CONSTRAINT CONSTRAINT_E4 UNIQUE (USERNAME),
	CONSTRAINT CONSTRAINT_E49 PRIMARY KEY (ID),
	CONSTRAINT FKOKMC0M1YICO9HMTE4W16WGJVW FOREIGN KEY (USER_ID) REFERENCES PUBLIC.USER_POS(ID) ON DELETE RESTRICT ON UPDATE RESTRICT
);

CREATE TABLE PUBLIC.CASHSESSION (
	DIFFERENCE NUMERIC(38,2),
	INITIALBALANCE NUMERIC(38,2) NOT NULL,
	REPORTEDBALANCE NUMERIC(38,2),
	TOTALSALES NUMERIC(38,2),
	TOTALEXPENSES NUMERIC(38,2),
	CLOSINGDATE TIMESTAMP,
	OPENINGDATE TIMESTAMP NOT NULL,
	CLOSED_BY_ID UUID,
	ID UUID NOT NULL,
	OPENED_BY_ID UUID,
	NOTE CHARACTER VARYING,
	STATUS ENUM('CLOSED', 'OPEN'),
	CONSTRAINT CONSTRAINT_E9 PRIMARY KEY (ID),
	CONSTRAINT FKHKKIY8IAEUD3EA5AQK4TDK1QC FOREIGN KEY (OPENED_BY_ID) REFERENCES PUBLIC.USER_POS(ID) ON DELETE RESTRICT ON UPDATE RESTRICT,
	CONSTRAINT FKJS8T67IHRFO72G5XLHUBS5S3E FOREIGN KEY (CLOSED_BY_ID) REFERENCES PUBLIC.USER_POS(ID) ON DELETE RESTRICT ON UPDATE RESTRICT
);

CREATE TABLE PUBLIC.CATEGORY_AVAILABLE_DAYS (
	CATEGORY_ID UUID NOT NULL,
	DAY_OF_WEEK ENUM('FRIDAY', 'MONDAY', 'SATURDAY', 'SUNDAY', 'THURSDAY', 'TUESDAY', 'WEDNESDAY') NOT NULL,
	CONSTRAINT CONSTRAINT_7 PRIMARY KEY (CATEGORY_ID,DAY_OF_WEEK),
	CONSTRAINT FKSS606WIIF65X2IA8TFQWON4BN FOREIGN KEY (CATEGORY_ID) REFERENCES PUBLIC.CATEGORY(ID) ON DELETE RESTRICT ON UPDATE RESTRICT
);

CREATE TABLE PUBLIC.CATEGORY_PRODUCT (
	CATEGORY_ID UUID NOT NULL,
	PRODUCT_ID UUID NOT NULL,
	CONSTRAINT CONSTRAINT_C PRIMARY KEY (CATEGORY_ID,PRODUCT_ID),
	CONSTRAINT FK55QIX17XKIMF4QTVDESJ17IGH FOREIGN KEY (PRODUCT_ID) REFERENCES PUBLIC.PRODUCT(ID) ON DELETE RESTRICT ON UPDATE RESTRICT,
	CONSTRAINT FK93BALDCQYK0PNF4LBFRQ4LIB5 FOREIGN KEY (CATEGORY_ID) REFERENCES PUBLIC.CATEGORY(ID) ON DELETE RESTRICT ON UPDATE RESTRICT
);

CREATE TABLE PUBLIC.INVITATION (
	CREATEDAT TIMESTAMP NOT NULL,
	EXPIRESAT TIMESTAMP NOT NULL,
	USEDAT TIMESTAMP,
	ID UUID NOT NULL,
	USER_ID UUID NOT NULL,
	TOKEN CHARACTER VARYING(255) NOT NULL,
	CONSTRAINT CONSTRAINT_6 UNIQUE (TOKEN),
	CONSTRAINT CONSTRAINT_64 PRIMARY KEY (ID),
	CONSTRAINT FKQHRI2VER75OUOB5VERV508C6T FOREIGN KEY (USER_ID) REFERENCES PUBLIC.USER_POS(ID) ON DELETE RESTRICT ON UPDATE RESTRICT
);

CREATE TABLE PUBLIC.PRODUCT_AVAILABLE_DAYS (
	PRODUCT_ID UUID NOT NULL,
	DAY_OF_WEEK ENUM('FRIDAY', 'MONDAY', 'SATURDAY', 'SUNDAY', 'THURSDAY', 'TUESDAY', 'WEDNESDAY') NOT NULL,
	CONSTRAINT CONSTRAINT_F1 PRIMARY KEY (PRODUCT_ID,DAY_OF_WEEK),
	CONSTRAINT FK2PPOOBVAJ1S8L5XS9OXMOWFT0 FOREIGN KEY (PRODUCT_ID) REFERENCES PUBLIC.PRODUCT(ID) ON DELETE RESTRICT ON UPDATE RESTRICT
);

CREATE TABLE PUBLIC.TICKET (
	DINERCOUNT INTEGER NOT NULL,
	TOTALAMOUNT NUMERIC(38,2) NOT NULL,
	CLOSEDAT TIMESTAMP,
	CREATEDAT TIMESTAMP,
	UPDATEDAT TIMESTAMP,
	ID UUID NOT NULL,
	USER_ID UUID NOT NULL,
	STATUS ENUM('CANCELED', 'OPEN', 'PAID') NOT NULL,
	TABLESNAPSHOT JSON,
	CONSTRAINT CONSTRAINT_9 PRIMARY KEY (ID),
	CONSTRAINT FK1VDL14UM7AXD8RC6DAHO7ATFU FOREIGN KEY (USER_ID) REFERENCES PUBLIC.USER_POS(ID) ON DELETE RESTRICT ON UPDATE RESTRICT
);

CREATE TABLE PUBLIC.TICKETITEM (
	UNITPRICE NUMERIC(38,2) NOT NULL,
	CREATEDAT TIMESTAMP NOT NULL,
	UPDATEDAT TIMESTAMP,
	AUTHOR_ID UUID NOT NULL,
	ID UUID NOT NULL,
	ORIGINALPRODUCTID UUID,
	TICKET_ID UUID,
	PRODUCTNAME CHARACTER VARYING(255) NOT NULL,
	PRODUCTSNAPSHOT JSON,
	STATUS ENUM('ADDED', 'CANCELED', 'ORDERED', 'PAID', 'SERVED') NOT NULL,
	CONSTRAINT CONSTRAINT_99 PRIMARY KEY (ID),
	CONSTRAINT FKIYE407WPVEOS507R9FPNMSOM9 FOREIGN KEY (TICKET_ID) REFERENCES PUBLIC.TICKET(ID) ON DELETE RESTRICT ON UPDATE RESTRICT,
	CONSTRAINT FKONFXJPKEH0HKC3PKBD7V6BFCI FOREIGN KEY (AUTHOR_ID) REFERENCES PUBLIC.USER_POS(ID) ON DELETE RESTRICT ON UPDATE RESTRICT
);

CREATE TABLE PUBLIC.PAYMENT (
	AMOUNT NUMERIC(38,2) NOT NULL,
	CHANGEGIVEN NUMERIC(38,2),
	CREATEDAT TIMESTAMP NOT NULL,
	ID UUID NOT NULL,
	TICKET_ID UUID NOT NULL,
	EXTERNALREFERENCE CHARACTER VARYING(255),
	"METHOD" ENUM('CASH', 'CREDIT_CARD', 'DEBIT_CARD', 'OTHER', 'TRANSFER') NOT NULL,
	CONSTRAINT CONSTRAINT_F PRIMARY KEY (ID),
	CONSTRAINT FKA8060TN2AHF51M5DKUJNPEROT FOREIGN KEY (TICKET_ID) REFERENCES PUBLIC.TICKET(ID) ON DELETE RESTRICT ON UPDATE RESTRICT
);

CREATE TABLE PUBLIC.RESTAURANTTABLE (
	HEIGHT INTEGER,
	POSX INTEGER NOT NULL,
	POSY INTEGER NOT NULL,
	WIDTH INTEGER,
	CREATEDAT TIMESTAMP NOT NULL,
	UPDATEDAT TIMESTAMP,
	FLOOR_ID UUID,
	ID UUID NOT NULL,
	TICKET_ID UUID,
	NAME CHARACTER VARYING(255) NOT NULL,
	STATUS ENUM('AVAILABLE', 'CLEANING', 'NOT_AVAILABLE', 'OCCUPIED', 'RESERVED') NOT NULL,
	CONSTRAINT CONSTRAINT_FE UNIQUE (TICKET_ID),
	CONSTRAINT CONSTRAINT_FE9 PRIMARY KEY (ID),
	CONSTRAINT FKJQQMN2AHEVT8H7ISFHC2MR0H1 FOREIGN KEY (TICKET_ID) REFERENCES PUBLIC.TICKET(ID) ON DELETE RESTRICT ON UPDATE RESTRICT,
	CONSTRAINT FKLGKO8WGQ5G9UTTDTBPTNTEADQ FOREIGN KEY (FLOOR_ID) REFERENCES PUBLIC.FLOOR(ID) ON DELETE RESTRICT ON UPDATE RESTRICT
);

CREATE TABLE PUBLIC.EXPENSE (
    ID UUID PRIMARY KEY,
    DESCRIPTION CHARACTER VARYING(255) NOT NULL,
    AMOUNT NUMERIC(38,2) NOT NULL,
    CATEGORY ENUM('SUPPLIES', 'CLEANING', 'MAINTENANCE', 'WAGES', 'OTHER') NOT NULL,
    CREATEDAT TIMESTAMP NOT NULL,
    CREATED_BY_USER_ID UUID NOT NULL,
    CONSTRAINT fK_EXPENSE_USER FOREIGN KEY (CREATED_BY_USER_ID) REFERENCES PUBLIC.USER_POS(ID)
);