/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * com.gdgguadalajara.pos API
 * OpenAPI spec version: 1.0.0-SNAPSHOT
 */
import type {
  Account,
  ActivateAccountRequest
} from '../../models';

import { customFetch } from '.././CustomFetch';

/**
 * @summary Activate Account
 */
export type postApiAccountsActivateResponse200 = {
  data: Account
  status: 200
}

export type postApiAccountsActivateResponse400 = {
  data: void
  status: 400
}
    
export type postApiAccountsActivateResponseSuccess = (postApiAccountsActivateResponse200) & {
  headers: Headers;
};
export type postApiAccountsActivateResponseError = (postApiAccountsActivateResponse400) & {
  headers: Headers;
};

export type postApiAccountsActivateResponse = (postApiAccountsActivateResponseSuccess | postApiAccountsActivateResponseError)

export const getPostApiAccountsActivateUrl = () => {


  

  return `/api/accounts/activate`
}

export const postApiAccountsActivate = async (activateAccountRequest: ActivateAccountRequest, options?: RequestInit): Promise<postApiAccountsActivateResponse> => {
  
  return customFetch<postApiAccountsActivateResponse>(getPostApiAccountsActivateUrl(),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      activateAccountRequest,)
  }
);}


