/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * com.gdgguadalajara.pos API
 * OpenAPI spec version: 1.0.0-SNAPSHOT
 */
import type {
  TicketItem,
  Uuid
} from '../../models';

import { customFetch } from '.././CustomFetch';

/**
 * @summary Create
 */
export type postApiTicketsTicketIdItemsProductIdResponse200 = {
  data: TicketItem
  status: 200
}

export type postApiTicketsTicketIdItemsProductIdResponse401 = {
  data: void
  status: 401
}

export type postApiTicketsTicketIdItemsProductIdResponse403 = {
  data: void
  status: 403
}
    
export type postApiTicketsTicketIdItemsProductIdResponseSuccess = (postApiTicketsTicketIdItemsProductIdResponse200) & {
  headers: Headers;
};
export type postApiTicketsTicketIdItemsProductIdResponseError = (postApiTicketsTicketIdItemsProductIdResponse401 | postApiTicketsTicketIdItemsProductIdResponse403) & {
  headers: Headers;
};

export type postApiTicketsTicketIdItemsProductIdResponse = (postApiTicketsTicketIdItemsProductIdResponseSuccess | postApiTicketsTicketIdItemsProductIdResponseError)

export const getPostApiTicketsTicketIdItemsProductIdUrl = (ticketId: Uuid,
    productId: Uuid,) => {


  

  return `/api/tickets/${ticketId}/items/${productId}`
}

export const postApiTicketsTicketIdItemsProductId = async (ticketId: Uuid,
    productId: Uuid, options?: RequestInit): Promise<postApiTicketsTicketIdItemsProductIdResponse> => {
  
  return customFetch<postApiTicketsTicketIdItemsProductIdResponse>(getPostApiTicketsTicketIdItemsProductIdUrl(ticketId,productId),
  {      
    ...options,
    method: 'POST'
    
    
  }
);}


