/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * com.gdgguadalajara.pos API
 * OpenAPI spec version: 1.0.0-SNAPSHOT
 */
import type {
  GetApiUsersParams,
  PaginatedResponseUser
} from '../../models';

import { customFetch } from '.././CustomFetch';

/**
 * @summary Get All
 */
export type getApiUsersResponse200 = {
  data: PaginatedResponseUser
  status: 200
}

export type getApiUsersResponse401 = {
  data: void
  status: 401
}

export type getApiUsersResponse403 = {
  data: void
  status: 403
}
    
export type getApiUsersResponseSuccess = (getApiUsersResponse200) & {
  headers: Headers;
};
export type getApiUsersResponseError = (getApiUsersResponse401 | getApiUsersResponse403) & {
  headers: Headers;
};

export type getApiUsersResponse = (getApiUsersResponseSuccess | getApiUsersResponseError)

export const getGetApiUsersUrl = (params?: GetApiUsersParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/api/users?${stringifiedParams}` : `/api/users`
}

export const getApiUsers = async (params?: GetApiUsersParams, options?: RequestInit): Promise<getApiUsersResponse> => {
  
  return customFetch<getApiUsersResponse>(getGetApiUsersUrl(params),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}


