/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * com.gdgguadalajara.pos API
 * OpenAPI spec version: 1.0.0-SNAPSHOT
 */
import type {
  Category,
  CreateCategoryRequest,
  GetApiCategoriesParams,
  PaginatedResponseCategory,
  UpdateCategoryRequest,
  Uuid
} from '../../models';

import { customFetch } from '.././CustomFetch';

/**
 * @summary Read
 */
export type getApiCategoriesResponse200 = {
  data: PaginatedResponseCategory
  status: 200
}

export type getApiCategoriesResponse401 = {
  data: void
  status: 401
}

export type getApiCategoriesResponse403 = {
  data: void
  status: 403
}
    
export type getApiCategoriesResponseSuccess = (getApiCategoriesResponse200) & {
  headers: Headers;
};
export type getApiCategoriesResponseError = (getApiCategoriesResponse401 | getApiCategoriesResponse403) & {
  headers: Headers;
};

export type getApiCategoriesResponse = (getApiCategoriesResponseSuccess | getApiCategoriesResponseError)

export const getGetApiCategoriesUrl = (params?: GetApiCategoriesParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/api/categories?${stringifiedParams}` : `/api/categories`
}

export const getApiCategories = async (params?: GetApiCategoriesParams, options?: RequestInit): Promise<getApiCategoriesResponse> => {
  
  return customFetch<getApiCategoriesResponse>(getGetApiCategoriesUrl(params),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}


/**
 * @summary Create
 */
export type postApiCategoriesResponse200 = {
  data: Category
  status: 200
}

export type postApiCategoriesResponse400 = {
  data: void
  status: 400
}

export type postApiCategoriesResponse401 = {
  data: void
  status: 401
}

export type postApiCategoriesResponse403 = {
  data: void
  status: 403
}
    
export type postApiCategoriesResponseSuccess = (postApiCategoriesResponse200) & {
  headers: Headers;
};
export type postApiCategoriesResponseError = (postApiCategoriesResponse400 | postApiCategoriesResponse401 | postApiCategoriesResponse403) & {
  headers: Headers;
};

export type postApiCategoriesResponse = (postApiCategoriesResponseSuccess | postApiCategoriesResponseError)

export const getPostApiCategoriesUrl = () => {


  

  return `/api/categories`
}

export const postApiCategories = async (createCategoryRequest: CreateCategoryRequest, options?: RequestInit): Promise<postApiCategoriesResponse> => {
  
  return customFetch<postApiCategoriesResponse>(getPostApiCategoriesUrl(),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      createCategoryRequest,)
  }
);}


/**
 * @summary Update
 */
export type putApiCategoriesUuidResponse200 = {
  data: Category
  status: 200
}

export type putApiCategoriesUuidResponse400 = {
  data: void
  status: 400
}

export type putApiCategoriesUuidResponse401 = {
  data: void
  status: 401
}

export type putApiCategoriesUuidResponse403 = {
  data: void
  status: 403
}
    
export type putApiCategoriesUuidResponseSuccess = (putApiCategoriesUuidResponse200) & {
  headers: Headers;
};
export type putApiCategoriesUuidResponseError = (putApiCategoriesUuidResponse400 | putApiCategoriesUuidResponse401 | putApiCategoriesUuidResponse403) & {
  headers: Headers;
};

export type putApiCategoriesUuidResponse = (putApiCategoriesUuidResponseSuccess | putApiCategoriesUuidResponseError)

export const getPutApiCategoriesUuidUrl = (uuid: Uuid,) => {


  

  return `/api/categories/${uuid}`
}

export const putApiCategoriesUuid = async (uuid: Uuid,
    updateCategoryRequest: UpdateCategoryRequest, options?: RequestInit): Promise<putApiCategoriesUuidResponse> => {
  
  return customFetch<putApiCategoriesUuidResponse>(getPutApiCategoriesUuidUrl(uuid),
  {      
    ...options,
    method: 'PUT',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      updateCategoryRequest,)
  }
);}


/**
 * @summary Read By Id
 */
export type getApiCategoriesUuidResponse200 = {
  data: Category
  status: 200
}

export type getApiCategoriesUuidResponse401 = {
  data: void
  status: 401
}

export type getApiCategoriesUuidResponse403 = {
  data: void
  status: 403
}
    
export type getApiCategoriesUuidResponseSuccess = (getApiCategoriesUuidResponse200) & {
  headers: Headers;
};
export type getApiCategoriesUuidResponseError = (getApiCategoriesUuidResponse401 | getApiCategoriesUuidResponse403) & {
  headers: Headers;
};

export type getApiCategoriesUuidResponse = (getApiCategoriesUuidResponseSuccess | getApiCategoriesUuidResponseError)

export const getGetApiCategoriesUuidUrl = (uuid: Uuid,) => {


  

  return `/api/categories/${uuid}`
}

export const getApiCategoriesUuid = async (uuid: Uuid, options?: RequestInit): Promise<getApiCategoriesUuidResponse> => {
  
  return customFetch<getApiCategoriesUuidResponse>(getGetApiCategoriesUuidUrl(uuid),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}


/**
 * @summary Delete
 */
export type deleteApiCategoriesUuidResponse204 = {
  data: void
  status: 204
}

export type deleteApiCategoriesUuidResponse401 = {
  data: void
  status: 401
}

export type deleteApiCategoriesUuidResponse403 = {
  data: void
  status: 403
}
    
export type deleteApiCategoriesUuidResponseSuccess = (deleteApiCategoriesUuidResponse204) & {
  headers: Headers;
};
export type deleteApiCategoriesUuidResponseError = (deleteApiCategoriesUuidResponse401 | deleteApiCategoriesUuidResponse403) & {
  headers: Headers;
};

export type deleteApiCategoriesUuidResponse = (deleteApiCategoriesUuidResponseSuccess | deleteApiCategoriesUuidResponseError)

export const getDeleteApiCategoriesUuidUrl = (uuid: Uuid,) => {


  

  return `/api/categories/${uuid}`
}

export const deleteApiCategoriesUuid = async (uuid: Uuid, options?: RequestInit): Promise<deleteApiCategoriesUuidResponse> => {
  
  return customFetch<deleteApiCategoriesUuidResponse>(getDeleteApiCategoriesUuidUrl(uuid),
  {      
    ...options,
    method: 'DELETE'
    
    
  }
);}


