/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * com.gdgguadalajara.pos API
 * OpenAPI spec version: 1.0.0-SNAPSHOT
 */
import type {
  CreateInvitationRequest,
  GetApiInvitationsParams,
  Invitation,
  PaginatedResponseInvitation
} from '../../models';

import { customFetch } from '.././CustomFetch';

/**
 * @summary Read
 */
export type getApiInvitationsResponse200 = {
  data: PaginatedResponseInvitation
  status: 200
}

export type getApiInvitationsResponse401 = {
  data: void
  status: 401
}

export type getApiInvitationsResponse403 = {
  data: void
  status: 403
}
    
export type getApiInvitationsResponseSuccess = (getApiInvitationsResponse200) & {
  headers: Headers;
};
export type getApiInvitationsResponseError = (getApiInvitationsResponse401 | getApiInvitationsResponse403) & {
  headers: Headers;
};

export type getApiInvitationsResponse = (getApiInvitationsResponseSuccess | getApiInvitationsResponseError)

export const getGetApiInvitationsUrl = (params?: GetApiInvitationsParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/api/invitations?${stringifiedParams}` : `/api/invitations`
}

export const getApiInvitations = async (params?: GetApiInvitationsParams, options?: RequestInit): Promise<getApiInvitationsResponse> => {
  
  return customFetch<getApiInvitationsResponse>(getGetApiInvitationsUrl(params),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}


/**
 * @summary Create
 */
export type postApiInvitationsResponse200 = {
  data: Invitation
  status: 200
}

export type postApiInvitationsResponse400 = {
  data: void
  status: 400
}

export type postApiInvitationsResponse401 = {
  data: void
  status: 401
}

export type postApiInvitationsResponse403 = {
  data: void
  status: 403
}
    
export type postApiInvitationsResponseSuccess = (postApiInvitationsResponse200) & {
  headers: Headers;
};
export type postApiInvitationsResponseError = (postApiInvitationsResponse400 | postApiInvitationsResponse401 | postApiInvitationsResponse403) & {
  headers: Headers;
};

export type postApiInvitationsResponse = (postApiInvitationsResponseSuccess | postApiInvitationsResponseError)

export const getPostApiInvitationsUrl = () => {


  

  return `/api/invitations`
}

export const postApiInvitations = async (createInvitationRequest: CreateInvitationRequest, options?: RequestInit): Promise<postApiInvitationsResponse> => {
  
  return customFetch<postApiInvitationsResponse>(getPostApiInvitationsUrl(),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      createInvitationRequest,)
  }
);}


/**
 * @summary Read By Token
 */
export type getApiInvitationsTokenResponse200 = {
  data: Invitation
  status: 200
}
    
export type getApiInvitationsTokenResponseSuccess = (getApiInvitationsTokenResponse200) & {
  headers: Headers;
};
;

export type getApiInvitationsTokenResponse = (getApiInvitationsTokenResponseSuccess)

export const getGetApiInvitationsTokenUrl = (token: string,) => {


  

  return `/api/invitations/${token}`
}

export const getApiInvitationsToken = async (token: string, options?: RequestInit): Promise<getApiInvitationsTokenResponse> => {
  
  return customFetch<getApiInvitationsTokenResponse>(getGetApiInvitationsTokenUrl(token),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}


