/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * com.gdgguadalajara.pos API
 * OpenAPI spec version: 1.0.0-SNAPSHOT
 */
import type {
  AuthenticateRequest,
  AuthenticateResponse,
  User
} from '../../models';

import { customFetch } from '.././CustomFetch';

/**
 * @summary Whoami
 */
export type getApiAuthResponse200 = {
  data: User
  status: 200
}

export type getApiAuthResponse401 = {
  data: void
  status: 401
}

export type getApiAuthResponse403 = {
  data: void
  status: 403
}
    
export type getApiAuthResponseSuccess = (getApiAuthResponse200) & {
  headers: Headers;
};
export type getApiAuthResponseError = (getApiAuthResponse401 | getApiAuthResponse403) & {
  headers: Headers;
};

export type getApiAuthResponse = (getApiAuthResponseSuccess | getApiAuthResponseError)

export const getGetApiAuthUrl = () => {


  

  return `/api/auth`
}

export const getApiAuth = async ( options?: RequestInit): Promise<getApiAuthResponse> => {
  
  return customFetch<getApiAuthResponse>(getGetApiAuthUrl(),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}


/**
 * @summary Auth
 */
export type postApiAuthResponse200 = {
  data: AuthenticateResponse
  status: 200
}

export type postApiAuthResponse400 = {
  data: void
  status: 400
}
    
export type postApiAuthResponseSuccess = (postApiAuthResponse200) & {
  headers: Headers;
};
export type postApiAuthResponseError = (postApiAuthResponse400) & {
  headers: Headers;
};

export type postApiAuthResponse = (postApiAuthResponseSuccess | postApiAuthResponseError)

export const getPostApiAuthUrl = () => {


  

  return `/api/auth`
}

export const postApiAuth = async (authenticateRequest: AuthenticateRequest, options?: RequestInit): Promise<postApiAuthResponse> => {
  
  return customFetch<postApiAuthResponse>(getPostApiAuthUrl(),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      authenticateRequest,)
  }
);}


